### ISSUE TITLE
Question: What is the recommended standard+/core library (or libraries)?

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/wiki#2]
E.g. one missing piece I quickly encountered was the lack of an Option module.

So should we go with Core or Batteries Included, or should there be an entirely separate bs core library? And how do you set this up and get it working?

**Comment by bobzhang** [comment]
what do you think if we provide a stdlib from scratch or fork from containers?

**Comment by ghost** [comment]
I would vote for starting a new stdlib, Core has some some C FFI if I remember correctly. Had very limited experience for Batteries Included.

**Comment by glennsl** [comment]
I'm not familiar enough with the offerings to have much of an opinion at all, but at least basing it off one of the existing libraries seems like a good idea. Both for familiarity and speed of implementation.

I'm also fond of the [Rust standard library](https://doc.rust-lang.org/std/#modules) which is very well thought out.

**Comment by bobzhang** [comment]
The thing is that JS already have quite  a decent standardized library, I would suggest we make 
bindings for JS part first, and then polyfill for the native port

**Comment by glennsl** [comment]
I agree for the JS part of it, but there are some very pervasively used idioms of OCaml that have no JS counterpart, like `option`, which I'd very much like to be able to use even when making the JS bindings.

**Comment by chenglou** [comment]
@dorafmon The stripped-down Core (Base, itself a stripped-down Core_kernel) is platform-agnostic.
I'd like to avoid yet another stdlib. If you wanna go with Containers then sure. Or Batteries, or Base.

**Comment by ghost** [comment]
@chenglou yeah I did a bit research after I post, Base is the deriving ppx a lot and I am not sure BS support it well. We can try to use containers which I think is mostly vanilla OCaml. I haven't tried it yet but would do some research this weekend.
