### ISSUE TITLE
Question: What's the (unit) test story?

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/wiki#3]
I imagine the various js unit test frameworks will be a challenge to port over in any ergonomic way. So... [OUnit](http://ounit.forge.ocamlcore.org/)?

**Comment by chenglou** [comment]
How about jest bindings, then convert jest to native?

**Comment by chenglou** [comment]
Ok, answered, and pointed to jest bindings + ounit. Feel free to tweak the wording.
