### ISSUE TITLE
Kill it!

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/wiki#9]
@chenglou I think we can kill this now. The content has (mostly) been moved to the new website. See
https://github.com/reasonml/reasonml.github.io/pull/133
https://github.com/reasonml/reasonml.github.io/pull/135
https://github.com/reasonml/reasonml.github.io/issues/134

**Comment by chenglou** [comment]
Awesome, love cleanups like these =)

I'll move this to the reasonml-old org to avoid breaking links.

**Comment by chenglou** [comment]
Oh, what about this? https://github.com/reasonml-community/wiki/blob/master/contrib-compiler.md

**Comment by glennsl** [comment]
Bob moved it over to the bs wiki a while ago: https://github.com/BuckleScript/bucklescript/wiki/Contribute

**Comment by chenglou** [comment]
Done =)
